CREATE SCHEMA IF NOT EXISTS ESTUDO_DIRIGIDO DEFAULT CHARACTER SET utf8;
USE ESTUDO_DIRIGIDO;
CREATE TABLE IF NOT EXISTS ESTUDO_DIRIGIDO.alunos(
Nome VARCHAR(40) NULL,
idade TINYINT (3) NULL,
Sexo CHAR(1) NULL,
Altura FLOAT NULL,
Peso FLOAT NULL,
Nacionalidade VARCHAR(30) default 'teste');

drop table alunos;