-- AVAIAÇÃO DE BANCO DE DADOS - 2o ANO F - DATA: 22/03/2023 --
-- ORIENTAÇÕES: AS RESPONSTAS DEVEM SER INSERIDAS EM ARQUIVO SCRIPT SQL NO FORMATO DE COMENTÁRIOS, QUANDO FOR MAIS DE UMA LINHA UTILIEZE
-- /* NO INÍCIO E NO FINAL DO COMENTÁRIO */ E QUANDO FOR SOMENTE DE UMA LINHA UTILIZE --

-- 01. CRIE UM BANCO DE DADOS COM O NOME DE "PROVA".


-- 02. FORMULE UM CONCEITO PARA BANCO DE DADOS 


-- 03. FORMULE UM CONCEITO DE CHAVE PRIMÁRIA 


-- 04. CONSTRUA A TABELA ABAIXO NO BANCO PROVA

CREATE TABLE IF NOT EXISTS `PROVA`.`CADASTRO` (
  NOME_CLIENTE VARCHAR(45),
  NASCIMENTO_CLIENTE DATE, 
  NACIONALIDADE_CLIENTE VARCHAR(45),
  SEXO_CLIENTE CHAR(1),
  CONTATO_CLIENTE VARCHAR(20),
  CPF_CLIENTE INT,
  CIDADE_CLIENTE VARCHAR(25)
  ) ENGINE = InnoDB;
  
-- 05. RECONSTRUIR A TABELA ACIMA REDEFININDO OS CAMPOS COM MELHOR ESTRUTURA E INSERINDO COMENTÁRIO LINHA A LINHA


-- 06. CRIAR UM CAMPO CHAVE NA TABELA DA QUESTÃO 04


-- 07. ADD O CAMPO IDENTIDADE DEPOIS DO CAMPO CPF.


-- 08. POVOAR A TABELA DA QUESTÃO 04 COM O MAIOR NÚMERO DE REGISTRO POSSIVEIS


-- 09. CONSTRUIR PELO MENOS TRÊSCONSULTAS UTILIZANDO OS  COMANDOS "ORDER BY", "WHERE" E "LIKE"
